workflows:
  docker-build:
    name: Docker Build

    environment:
      docker: true

    scripts:
      - name: Check files
        script: ls -la

      - name: Build system
        script: |
          chmod +x build-all.sh
          ./build-all.sh

    artifacts:
      - "**/*.log"